set(__QT_DEPLOY_TARGET_boombox_FILE /var/home/esox/dev/cpp/boombox/build-gst/bin/boombox)
set(__QT_DEPLOY_TARGET_boombox_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_test_logger_exe_FILE /var/home/esox/dev/cpp/boombox/build-gst/bin/test_logger_exe)
set(__QT_DEPLOY_TARGET_test_logger_exe_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_test_error_handling_FILE /var/home/esox/dev/cpp/boombox/build-gst/bin/test_error_handling)
set(__QT_DEPLOY_TARGET_test_error_handling_TYPE EXECUTABLE)
